services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql   # Persist data even if container is removed
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        labels: "${APP_ENV},db"
        env: "${APP_ENV}"
        compress: "true"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=${APP_ENV}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        labels: "${APP_ENV},app"
        env: "${APP_ENV}"
        compress: "true"

  redis:
    image: redis:alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 25M
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        labels: "${APP_ENV},redis"
        env: "${APP_ENV}"
        compress: "true"

  k6:
    image: grafana/k6
    volumes:
      - ./test:/app/test
    command: ["--help"]

volumes:
  db-data:
